version: "3.9"

name: tracing-demo

services:
  demo:
    build:
      context: .
    ports:
      - "8080:8080"
    environment: 
      OTEL_EXPORTER_JAEGER_AGENT_HOST: "jaeger"
      OTEL_EXPORTER_JAEGER_AGENT_PORT: "6831"
      USE_OTEL: true
  jaeger:
      image: jaegertracing/all-in-one:latest
      expose:
        - "5775/udp"
        - "6831/udp"
        - "6832/udp"
        - "5778"
        - "14268"
        - "9411"
      ports:
        - "16686:16686"
